### ISSUE TITLE
Unable to use s3 glob patterns with read_yaml

### ISSUE THREAD

**Issue by kinghuang** [teaguesterling/duckdb_yaml#7]
I'm trying to use the `read_yaml` function to read several YAML files in a S3 bucket. Specifying an individual object works. But, using a glob pattern doesn't.

**The glob function works.**

```sql
select * from glob('s3://bucket/prefix/*.yaml');
```

```
┌─────────────────────────────────┐
│             file                │
│           varchar               │
├─────────────────────────────────┤
│ s3://bucket/prefix/key-1.yaml   │
│ s3://bucket/prefix/key-2.yaml   │
│ s3://bucket/prefix/key-3.yaml   │
├─────────────────────────────────┤
│            3 rows               │
└─────────────────────────────────┘
```

**Selecting from a single object works.**

```sql
select name from read_yaml('s3://bucket/prefix/key-1.yaml');
```

```
┌─────────────────┐
│      name       │
│     varchar     │
├─────────────────┤
│ emission-events │
└─────────────────┘
```

**Selecting from a glob pattern doesn't work.**

```sql
select name from read_yaml('s3://bucket/prefix/*.yaml');
```

```
IO Error:
No YAML files found matching the input path
```

**Comment by teaguesterling** [comment]
I suspect this is the same underlying issue as #6, which is next on the todo list.

**Comment by teaguesterling** [comment]
This should be fixed in the latest release (v1.0.1). I'll be will be requesting an update to the community extension soon. I need a good public test repo, however. If you have one, I can confirm.

**Comment by teaguesterling** [comment]
@kinghuang This should be resolved in the latest version now but I'd like to make sure it works for you before closing.

**Comment by kinghuang** [comment]
Hey, @teaguesterling. Sorry to keep you waiting! I'm still not having any luck using a glob pattern here. I've updated to the latest version.

```
D select extension_name, extension_version, installed_from, install_mode
  from duckdb_extensions()
  where extension_name = 'yaml';
┌────────────────┬───────────────────┬────────────────┬──────────────┐
│ extension_name │ extension_version │ installed_from │ install_mode │
│    varchar     │      varchar      │    varchar     │   varchar    │
├────────────────┼───────────────────┼────────────────┼──────────────┤
│ yaml           │ c613b17           │ community      │ REPOSITORY   │
└────────────────┴───────────────────┴────────────────┴──────────────┘
```

And, I'm getting a different IO Error now using a glob pattern.

```
D select * from read_yaml('s3://oxy-sbx-su-methane-ldar/cam-datasets/*.yaml');
IO Error:
Remote file does not exist or is not accessible: s3://oxy-sbx-su-methane-ldar/cam-datasets/*.yaml
```

Calling the `glob()` function with the same argument works.

**Comment by teaguesterling** [comment]
This is fixed in the latest build! There was a conflict between an undocumented weird directory reading feature and the way S3 was reporting prefixes as directories. Should be good once the build finishes.

**Comment by kinghuang** [comment]
> This is fixed in the latest build!

Awesome! I can confirm that commit [912c3d0](https://github.com/teaguesterling/duckdb_yaml/commit/912c3d002039d9ebed1574ade31ab87cdc1b4bc2) works for me.
